### ISSUE TITLE
Error when trying to load market.

### ISSUE THREAD

**Issue by petrucioinica99** [Bonfida/dex-v4#82]
When calling the Market.load function I am always greeted with the followng error:
`Unexpected 128 bytes after deserialized data
    at deserialize (index.js?8074:405:1)
    at MarketState.retrieve (state.js?92d6:51:1)
    at async Market.load (market.js?8329:55:1)
`
I am building the public key, market address and program id using the solana/web3 classes.
This is happening when trying to connect to the devnet.

**Comment by dr497** [comment]
What program ID are you using?

**Comment by tenuki** [comment]
I would like to know if there is any news about this issue. I tried to decode the market and it fails checking marketinfo header/padding: 

```
solana@pc18:~$ NODEURL=https://api.devnet.solana.com python3 pyparser.py --address Gdaxn4WkV2ZyNcMYsUWiAnmjy4YqSka4woy8ggazh4ba
Traceback (most recent call last):
  File "pyparser.py", line 175, in <module>
    market_d = parseData(market_st, data, b'serum', b'padding')
  File "pyparser.py", line 126, in parseData
    raise Exception("Invalid Prefix at: %r" % data )
Exception: Invalid Prefix at: b"\x01\x00\x00\x00\x00\x00\x00\x00Y\x99\x87N\x0cX\xc6\xdc\xc1y\\\xfe\xf3\xcb\x8ev-\xf9sx\x86j\x8a\xb7b\x912%\xfc6\xa4\xf4\xad%\xa6\x8b\x95\x9bT\x0f\xde\x0b\xbc\xc2\xf2\x94\xb7'\xd2\xbd\xabny\xe6\x0f\xa3\xee\x153\x88E\x13g_\x9d\xcf\x00\x87\xb5\x159_\xc1\x81\x94$\xe6\x1f\x15<8/PR\xce\xd8\xdc\xd4nI\xdeUO hP\xe8 \x1e\x9e\xbe`\xa3x,%t\x12\xe2\x10\x94s\x7ftG\xe4Hd\xe8\x82\x9fi\xb3\x12\xb4\xcc\xc36\xf1\x8a\xa0Z5\x11U\x15\\\x8d\xe1y\r\x0f0\x02\x13\xae\xa7\xb0\x9d\xa3\x84\xff\x12\xd66?\x92\xabM\xc5\xbd1\x8cOs\xa0$5\xb0#\xc3\x0e5[\xa3\xfe\x0f\x8e\x82\x07\x9c\n;0\xbd\xa0\t\xd8\xed\xa3\xa6\x975\xdd\xb8a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\x00\x00\x00\x00\x10'\x00\x00\x00\x00\x00\x00\xa0\x86\x01\x00\x00\x00\x00\x00@B\x0f\x00\x00\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00"
```

**Comment by mihneacalugaru** [comment]
The issue was that I was trying to use a programId from the mainnet while connecting to the devnet.  @tenuki make sure the program you are using is on the same net as the one provided in the connection url.

**Comment by petrucioinica99** [comment]
The issue was that I was trying to use a programId from the mainnet while connecting to the devnet. @tenuki make sure the program you are using is on the same net as the one provided in the connection url.
